import styled from 'styled-components'

export const AppRoot    = styled.div`min-height: 100vh; display: flex; flex-direction: column; background: ${p => p.theme.bg.page};`
export const Header     = styled.header`position: sticky; top: 0; z-index: 20; background: ${p => p.theme.bg.card}e0; backdrop-filter: blur(12px); border-bottom: 1px solid ${p => p.theme.border};`
export const HeaderInner= styled.div`max-width: 1280px; margin: 0 auto; padding: 0 1rem; height: 3.5rem; display: flex; align-items: center; justify-content: space-between; gap: 1rem;`
export const Logo       = styled.div`display: flex; align-items: center; gap: 0.5rem; flex-shrink: 0;`
export const LogoText   = styled.span`font-weight: 700; font-size: 0.9375rem; color: ${p => p.theme.text.primary}; @media (max-width: 640px) { display: none; }`
export const ThemeBtn   = styled.button`display: flex; align-items: center; justify-content: center; padding: 0.4rem; border: none; border-radius: ${p => p.theme.radius.md}; background: ${p => p.theme.bg.subtle}; color: ${p => p.theme.text.muted}; cursor: pointer; flex-shrink: 0; transition: all 0.15s; &:hover { color: ${p => p.theme.text.primary}; background: ${p => p.theme.bg.hover}; }`
export const Body       = styled.div`display: flex; flex: 1; max-width: 1280px; width: 100%; margin: 0 auto;`
export const Sidebar    = styled.aside`display: none; flex-direction: column; gap: 0.25rem; width: 11rem; flex-shrink: 0; padding: 1rem; border-right: 1px solid ${p => p.theme.border}; @media (min-width: 768px) { display: flex; }`
export const NavItem    = styled.button<{ $active: boolean }>`display: flex; align-items: center; gap: 0.625rem; padding: 0.625rem 0.75rem; border: none; border-radius: ${p => p.theme.radius.md}; font-family: ${p => p.theme.font.sans}; font-size: 0.875rem; font-weight: 500; cursor: pointer; text-align: left; transition: all 0.15s; width: 100%; background: ${p => p.$active ? p.theme.accent : 'transparent'}; color: ${p => p.$active ? 'white' : p.theme.text.muted}; &:hover { background: ${p => p.$active ? p.theme.accent : p.theme.bg.hover}; color: ${p => p.$active ? 'white' : p.theme.text.primary}; }`
export const Main       = styled.main`flex: 1; padding: 1rem; overflow: auto; @media (min-width: 768px) { padding: 1.5rem; }`
export const BottomNav  = styled.nav`display: flex; border-top: 1px solid ${p => p.theme.border}; background: ${p => p.theme.bg.card}f0; backdrop-filter: blur(12px); position: sticky; bottom: 0; z-index: 20; overflow-x: auto; @media (min-width: 768px) { display: none; }`
export const BottomItem = styled.button<{ $active: boolean }>`flex-shrink: 0; display: flex; flex-direction: column; align-items: center; gap: 0.2rem; padding: 0.625rem 0.75rem; font-size: 0.55rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; border: none; background: transparent; cursor: pointer; font-family: ${p => p.theme.font.sans}; color: ${p => p.$active ? p.theme.accent : p.theme.text.muted}; transition: color 0.15s;`
